#![allow(clippy::default_trait_access)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::struct_field_names)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
#![allow(dead_code)]

//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! OpenAI API
//! Source: /tmp/openapi.json
//! Version: 2.3.0
//! Generated by `oas3-gen v0.24.0`
//!
//! No description provided

use anyhow::Context;
use reqwest::{Client, Url};
use validator::Validate;
pub const BASE_URL: &str = "https://api.openai.com/v1";
#[derive(Debug, Clone)]
pub struct OpenAiApiClient {
    pub client: Client,
    pub base_url: Url,
}
impl Default for OpenAiApiClient {
    fn default() -> Self {
        Self::new()
    }
}
impl OpenAiApiClient {
    /// Create a client using the OpenAPI `servers[0]` URL.
    #[must_use]
    #[track_caller]
    pub fn new() -> Self {
        Self {
            client: Client::builder().build().expect("client"),
            base_url: Url::parse(BASE_URL).expect("valid base url"),
        }
    }
    /// Create a client with a custom base URL.
    pub fn with_base_url(base_url: impl AsRef<str>) -> anyhow::Result<Self> {
        Ok(Self {
            client: Client::builder().build().context("building reqwest client")?,
            base_url: Url::parse(base_url.as_ref()).context("parsing base url")?,
        })
    }
    /// Create a client from an existing `reqwest::Client`.
    pub fn with_client(
        base_url: impl AsRef<str>,
        client: Client,
    ) -> anyhow::Result<Self> {
        let url = Url::parse(base_url.as_ref()).context("parsing base url")?;
        Ok(Self { client, base_url: url })
    }
    ///Create response
    ///
    ///Creates a response.
    ///
    ///POST /responses
    pub async fn createresponse(
        &self,
        request: CreateresponseRequest,
    ) -> anyhow::Result<CreateresponseResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("responses");
        let mut req_builder = self.client.post(url);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(CreateresponseRequest::parse_response(response).await?)
    }
}

