#![allow(clippy::default_trait_access)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::struct_field_names)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
#![allow(dead_code)]

//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! OpenAI API
//! Source: /tmp/openapi.json
//! Version: 2.3.0
//! Generated by `oas3-gen v0.24.0`
//!
//! No description provided

use serde::{
    Deserialize,
    Serialize,
};
use validator::Validate;
static REGEX_FUNCTION_CALL_ITEM_PARAM_NAME: std::sync::LazyLock<regex::Regex> =
    std::sync::LazyLock::new(|| regex::Regex::new("^[a-zA-Z0-9_-]+$").expect("invalid regex"));
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct AllowedToolChoice {
    pub mode: ToolChoiceValueEnum,
    pub tools: Vec<ToolKind>,
    #[serde(rename = "type")]
    #[default(Some("allowed_tools".to_string()))]
    pub r#type: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct AllowedToolsParam {
    pub mode: Option<serde_json::Value>,
    ///The list of tools that are permitted for this request.
    #[validate(length(min = 1u64, max = 128u64), nested)]
    pub tools: Vec<SpecificFunctionParam>,
    ///The tool choice type. Always `allowed_tools`.
    #[serde(rename = "type")]
    #[default(Some("allowed_tools".to_string()))]
    pub r#type: Option<String>,
}
///An annotation that applies to a span of output text.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum Annotation {
    ///A citation for a web resource used to generate a model response.
    #[default]
    UrlCitationBody(UrlCitationBody),
}
///A piece of assistant message content, such as text or a refusal.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum ArrayKind {
    #[default]
    OutputText(OutputTextContentParam),
    Refusal(RefusalContentParam),
}
impl ArrayKind {
    pub fn output_text(text: String) -> Self {
        Self::OutputText(OutputTextContentParam {
            text,
            ..Default::default()
        })
    }
    pub fn refusal(refusal: String) -> Self {
        Self::Refusal(RefusalContentParam {
            refusal,
            ..Default::default()
        })
    }
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum ArrayKind2 {
    ///A text input to the model.
    #[default]
    InputTextContentParam(InputTextContentParam),
}
impl ArrayKind2 {
    ///A text input to the model.
    pub fn input_text_content_param(text: String) -> Self {
        Self::InputTextContentParam(InputTextContentParam {
            text,
            ..Default::default()
        })
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct AssistantMessageItemParam {
    ///The message content, as an array of content parts.
    pub content: AssistantMessageItemParamContent,
    pub id: Option<String>,
    ///The role of the message author. Always `assistant`.
    #[default(Some("assistant".to_string()))]
    pub role: Option<String>,
    pub status: Option<String>,
    ///The item type. Always `message`.
    #[serde(rename = "type")]
    #[default(Some("message".to_string()))]
    pub r#type: Option<String>,
}
///The message content, as an array of content parts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum AssistantMessageItemParamContent {
    #[default]
    Array(Vec<ArrayKind>),
    ///The message content, as a single string.
    String(String),
}
///A content part that makes up an input or output item.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum ContentKind {
    ///A text input to the model.
    #[default]
    InputText(InputTextContent),
    ///A text output from the model.
    OutputText(OutputTextContent),
    ///A text content.
    Text(TextContent),
    ///A summary text from the model.
    SummaryText(SummaryTextContent),
    ///Reasoning text from the model.
    ReasoningText(ReasoningTextContent),
    ///A refusal from the model.
    Refusal(RefusalContent),
    ///An image input to the model. Learn about [image inputs](/docs/guides/vision).
    InputImage(InputImageContent),
    ///A file input to the model.
    InputFile(InputFileContent),
    ///A content block representing a video input to the model.
    InputVideo(InputVideoContent),
}
impl ContentKind {
    ///A text input to the model.
    pub fn input_text(text: String) -> Self {
        Self::InputText(InputTextContent {
            text,
            ..Default::default()
        })
    }
    ///A text content.
    pub fn text(text: String) -> Self {
        Self::Text(TextContent {
            text,
            ..Default::default()
        })
    }
    ///A summary text from the model.
    pub fn summary_text(text: String) -> Self {
        Self::SummaryText(SummaryTextContent {
            text,
            ..Default::default()
        })
    }
    ///Reasoning text from the model.
    pub fn reasoning_text(text: String) -> Self {
        Self::ReasoningText(ReasoningTextContent {
            text,
            ..Default::default()
        })
    }
    ///A refusal from the model.
    pub fn refusal(refusal: String) -> Self {
        Self::Refusal(RefusalContent {
            refusal,
            ..Default::default()
        })
    }
    ///An image input to the model. Learn about [image inputs](/docs/guides/vision).
    pub fn input_image(detail: serde_json::Value) -> Self {
        Self::InputImage(InputImageContent {
            detail,
            ..Default::default()
        })
    }
    ///A file input to the model.
    pub fn input_file() -> Self {
        Self::InputFile(InputFileContent::default())
    }
    ///A content block representing a video input to the model.
    pub fn input_video(video_url: String) -> Self {
        Self::InputVideo(InputVideoContent {
            video_url,
            ..Default::default()
        })
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub struct CreateResponseBody {
    ///Whether to run the request in the background and return immediately.
    pub background: Option<bool>,
    pub frequency_penalty: Option<f64>,
    pub include: Option<Vec<IncludeEnum>>,
    pub input: Option<String>,
    pub instructions: Option<String>,
    pub max_output_tokens: Option<i64>,
    pub max_tool_calls: Option<i64>,
    pub metadata: Option<serde_json::Value>,
    pub model: Option<String>,
    pub parallel_tool_calls: Option<bool>,
    pub presence_penalty: Option<f64>,
    pub previous_response_id: Option<String>,
    pub prompt_cache_key: Option<String>,
    pub reasoning: Option<serde_json::Value>,
    pub safety_identifier: Option<String>,
    pub service_tier: Option<serde_json::Value>,
    ///Whether to store the response so it can be retrieved later.
    pub store: Option<bool>,
    ///Whether to stream response events as server-sent events.
    pub stream: Option<bool>,
    pub stream_options: Option<serde_json::Value>,
    pub temperature: Option<f64>,
    pub text: Option<serde_json::Value>,
    pub tool_choice: Option<serde_json::Value>,
    pub tools: Option<CreateResponseBodyTools>,
    pub top_logprobs: Option<i64>,
    pub top_p: Option<f64>,
    pub truncation: Option<serde_json::Value>,
}
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum CreateResponseBodyTools {
    ///A list of tools that the model may call while generating the response.
    #[default]
    Array(Vec<FunctionToolParam>),
}
///Creates a response.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct CreateresponseRequest {
    pub body: Option<CreateResponseBody>,
}
#[bon::bon]
impl CreateresponseRequest {
    ///Create a new request with the given parameters.
    #[builder]
    pub fn new(body: Option<CreateResponseBody>) -> anyhow::Result<Self> {
        let request = Self { body };
        request.validate()?;
        Ok(request)
    }
}
impl CreateresponseRequest {
    ///Parse the HTTP response into the response enum.
    pub async fn parse_response(req: reqwest::Response) -> anyhow::Result<CreateresponseResponse> {
        let status = req.status();
        if status.is_success() {
            let content_type_str = req
                .headers()
                .get(reqwest::header::CONTENT_TYPE)
                .and_then(|v| v.to_str().ok())
                .unwrap_or("application/json");
            if content_type_str.contains("event-stream") {
                let data = <oas3_gen_support::EventStream<Response200Response>>::from_response(req);
                return Ok(CreateresponseResponse::OkEventStream(data));
            }
            if content_type_str.contains("json") {
                let data =
                    oas3_gen_support::Diagnostics::<ResponseResource>::json_with_diagnostics(req)
                        .await?;
                return Ok(CreateresponseResponse::Ok(data));
            }
        }
        let _ = req.bytes().await?;
        return Ok(CreateresponseResponse::Unknown);
    }
}
///Response types for Createresponse
#[derive(Debug)]
pub enum CreateresponseResponse {
    ///200: Success
    Ok(ResponseResource),
    ///200: Success
    OkEventStream(oas3_gen_support::EventStream<Response200Response>),
    ///default: Unknown response
    Unknown,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct DeveloperMessageItemParam {
    ///The message content, as an array of content parts.
    pub content: MessageItemParamContent,
    pub id: Option<String>,
    ///The message role. Always `developer`.
    #[default(Some("developer".to_string()))]
    pub role: Option<String>,
    pub status: Option<String>,
    ///The item type. Always `message`.
    #[serde(rename = "type")]
    #[default(Some("message".to_string()))]
    pub r#type: Option<String>,
}
pub type EmptyModelParam = serde_json::Value;
///An error that occurred while generating the response.
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
pub struct Error {
    ///A machine-readable error code that was returned.
    #[validate(length(min = 1u64))]
    pub code: String,
    ///A human-readable description of the error that was returned.
    #[validate(length(min = 1u64))]
    pub message: String,
}
///An error payload that was emitted for a streaming error event.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
pub struct ErrorPayload {
    pub code: Option<String>,
    ///The response headers that were emitted with the error, if any.
    pub headers: Option<std::collections::HashMap<String, String>>,
    ///The human-readable error message that was emitted.
    #[validate(length(min = 1u64))]
    pub message: String,
    pub param: Option<String>,
    ///The error type that was emitted.
    #[serde(rename = "type")]
    #[validate(length(min = 1u64))]
    pub r#type: String,
}
///A streaming event that indicated an error was emitted.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct ErrorStreamingEvent {
    pub error: serde_json::Value,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `error`.
    #[serde(rename = "type")]
    #[default(Some("error".to_string()))]
    pub r#type: Option<String>,
}
///A function tool call that was generated by the model.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct FunctionCall {
    ///The arguments JSON string that was generated.
    pub arguments: String,
    ///The unique ID of the function tool call that was generated.
    pub call_id: String,
    ///The unique ID of the function call item.
    pub id: String,
    ///The name of the function that was called.
    pub name: String,
    pub status: serde_json::Value,
    ///The type of the item. Always `function_call`.
    #[serde(rename = "type")]
    #[default(Some("function_call".to_string()))]
    pub r#type: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct FunctionCallItemParam {
    ///The function arguments as a JSON string.
    #[validate(length(min = 1u64))]
    pub arguments: String,
    ///The unique ID of the function tool call generated by the model.
    #[validate(length(min = 1u64, max = 64u64))]
    pub call_id: String,
    pub id: Option<String>,
    ///The name of the function to call.
    #[validate(
        length(min = 1u64, max = 64u64),
        regex(path = "REGEX_FUNCTION_CALL_ITEM_PARAM_NAME")
    )]
    pub name: String,
    pub status: Option<serde_json::Value>,
    ///The item type. Always `function_call`.
    #[serde(rename = "type")]
    #[default(Some("function_call".to_string()))]
    pub r#type: Option<String>,
}
///A function tool call output that was returned by the tool.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct FunctionCallOutput {
    ///The unique ID of the function tool call generated by the model.
    pub call_id: String,
    ///The unique ID of the function tool call output. Populated when this item is returned via API.
    pub id: String,
    pub output: FunctionCallOutputOutput,
    pub status: serde_json::Value,
    ///The type of the function tool call output. Always `function_call_output`.
    #[serde(rename = "type")]
    #[default(Some("function_call_output".to_string()))]
    pub r#type: Option<String>,
}
///The output of a function tool call.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct FunctionCallOutputItemParam {
    ///The unique ID of the function tool call generated by the model.
    #[validate(length(min = 1u64, max = 64u64))]
    pub call_id: String,
    pub id: Option<String>,
    ///Text, image, or file output of the function tool call.
    pub output: FunctionCallOutputItemParamOutput,
    pub status: Option<serde_json::Value>,
    ///The type of the function tool call output. Always `function_call_output`.
    #[serde(rename = "type")]
    #[default(Some("function_call_output".to_string()))]
    pub r#type: Option<String>,
}
///Text, image, or file output of the function tool call.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum FunctionCallOutputItemParamOutput {
    ///A JSON string of the output of the function tool call.
    #[default]
    String(String),
    ///An array of content outputs (text, image, file) for the function tool call.
    Array(Vec<InputArrayKind>),
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum FunctionCallOutputOutput {
    ///A JSON string of the output of the function tool call.
    #[default]
    String(String),
    ///An array of output contents (images, files, text) for the function tool call.
    Array(Vec<InputContentKind>),
}
///Similar to `FunctionCallStatus`. All three options are allowed here for compatibility, but because in practice these items will be provided by developers, only `completed` should be used.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum FunctionCallOutputStatusEnum {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}
impl core::fmt::Display for FunctionCallOutputStatusEnum {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InProgress => write!(f, "in_progress"),
            Self::Completed => write!(f, "completed"),
            Self::Incomplete => write!(f, "incomplete"),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum FunctionCallStatus {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}
impl core::fmt::Display for FunctionCallStatus {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InProgress => write!(f, "in_progress"),
            Self::Completed => write!(f, "completed"),
            Self::Incomplete => write!(f, "incomplete"),
        }
    }
}
///Defines a function in your own code the model can choose to call. Learn more about [function calling](https://platform.openai.com/docs/guides/function-calling).
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct FunctionTool {
    pub description: Option<String>,
    ///The name of the function to call.
    #[validate(length(min = 1u64))]
    pub name: String,
    pub parameters: Option<std::collections::HashMap<String, serde_json::Value>>,
    pub strict: Option<bool>,
    ///The type of the function tool. Always `function`.
    #[serde(rename = "type")]
    #[default(Some("function".to_string()))]
    pub r#type: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct FunctionToolChoice {
    pub name: Option<String>,
    #[serde(rename = "type")]
    #[default(Some("function".to_string()))]
    pub r#type: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct FunctionToolParam {
    pub description: Option<String>,
    #[validate(
        length(min = 1u64, max = 64u64),
        regex(path = "REGEX_FUNCTION_CALL_ITEM_PARAM_NAME")
    )]
    pub name: String,
    pub parameters: Option<EmptyModelParam>,
    pub strict: Option<bool>,
    #[serde(rename = "type")]
    #[default(Some("function".to_string()))]
    pub r#type: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum ImageDetail {
    #[serde(rename = "low")]
    #[default]
    Low,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "auto")]
    Auto,
}
impl core::fmt::Display for ImageDetail {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Low => write!(f, "low"),
            Self::High => write!(f, "high"),
            Self::Auto => write!(f, "auto"),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, oas3_gen_support::Default)]
pub enum IncludeEnum {
    #[serde(rename = "reasoning.encrypted_content")]
    #[default]
    ReasoningEncryptedContent,
    #[serde(rename = "message.output_text.logprobs")]
    MessageOutputTextLogprobs,
}
impl core::fmt::Display for IncludeEnum {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::ReasoningEncryptedContent => write!(f, "reasoning.encrypted_content"),
            Self::MessageOutputTextLogprobs => write!(f, "message.output_text.logprobs"),
        }
    }
}
///Details about why the response was incomplete.
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
pub struct IncompleteDetails {
    ///The reason the response could not be completed.
    #[validate(length(min = 1u64))]
    pub reason: String,
}
///A piece of message content, such as text, an image, or a file.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum InputArrayKind {
    ///A text input to the model.
    #[default]
    TextContentParam(InputTextContentParam),
    ///An image input to the model. Learn about [image inputs](/docs/guides/vision)
    ImageContentParamAutoParam(InputImageContentParamAutoParam),
    ///A file input to the model.
    FileContentParam(InputFileContentParam),
    ///A content block representing a video input to the model.
    VideoContent(InputVideoContent),
}
impl InputArrayKind {
    ///A text input to the model.
    pub fn text_content_param(text: String) -> Self {
        Self::TextContentParam(InputTextContentParam {
            text,
            ..Default::default()
        })
    }
    ///An image input to the model. Learn about [image inputs](/docs/guides/vision)
    pub fn image_content_param_auto_param() -> Self {
        Self::ImageContentParamAutoParam(InputImageContentParamAutoParam::default())
    }
    ///A file input to the model.
    pub fn file_content_param() -> Self {
        Self::FileContentParam(InputFileContentParam::default())
    }
    ///A content block representing a video input to the model.
    pub fn video_content(video_url: String) -> Self {
        Self::VideoContent(InputVideoContent {
            video_url,
            ..Default::default()
        })
    }
}
///A content part that makes up an input or output item.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum InputContentKind {
    ///A text input to the model.
    #[default]
    Text(InputTextContent),
    ///An image input to the model. Learn about [image inputs](/docs/guides/vision).
    Image(InputImageContent),
    ///A file input to the model.
    File(InputFileContent),
}
impl InputContentKind {
    ///A text input to the model.
    pub fn text(text: String) -> Self {
        Self::Text(InputTextContent {
            text,
            ..Default::default()
        })
    }
    ///An image input to the model. Learn about [image inputs](/docs/guides/vision).
    pub fn image(detail: serde_json::Value) -> Self {
        Self::Image(InputImageContent {
            detail,
            ..Default::default()
        })
    }
    ///A file input to the model.
    pub fn file() -> Self {
        Self::File(InputFileContent::default())
    }
}
///A file input to the model.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct InputFileContent {
    ///The URL of the file to be sent to the model.
    pub file_url: Option<String>,
    ///The name of the file to be sent to the model.
    pub filename: Option<String>,
    ///The type of the input item. Always `input_file`.
    #[serde(rename = "type")]
    #[default(Some("input_file".to_string()))]
    pub r#type: Option<String>,
}
///A file input to the model.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct InputFileContentParam {
    pub file_data: Option<String>,
    pub file_url: Option<String>,
    pub filename: Option<String>,
    ///The type of the input item. Always `input_file`.
    #[serde(rename = "type")]
    #[default(Some("input_file".to_string()))]
    pub r#type: Option<String>,
}
///An image input to the model. Learn about [image inputs](/docs/guides/vision).
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct InputImageContent {
    pub detail: serde_json::Value,
    pub image_url: Option<String>,
    ///The type of the input item. Always `input_image`.
    #[serde(rename = "type")]
    #[default(Some("input_image".to_string()))]
    pub r#type: Option<String>,
}
///An image input to the model. Learn about [image inputs](/docs/guides/vision)
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct InputImageContentParamAutoParam {
    pub detail: Option<serde_json::Value>,
    pub image_url: Option<String>,
    ///The type of the input item. Always `input_image`.
    #[serde(rename = "type")]
    #[default(Some("input_image".to_string()))]
    pub r#type: Option<String>,
}
///A piece of message content, such as text, an image, or a file.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum InputParamKind {
    ///A text input to the model.
    #[default]
    TextContent(InputTextContentParam),
    ///An image input to the model. Learn about [image inputs](/docs/guides/vision)
    ImageContentParamAuto(InputImageContentParamAutoParam),
    ///A file input to the model.
    FileContent(InputFileContentParam),
}
impl InputParamKind {
    ///A text input to the model.
    pub fn text_content(text: String) -> Self {
        Self::TextContent(InputTextContentParam {
            text,
            ..Default::default()
        })
    }
    ///An image input to the model. Learn about [image inputs](/docs/guides/vision)
    pub fn image_content_auto() -> Self {
        Self::ImageContentParamAuto(InputImageContentParamAutoParam::default())
    }
    ///A file input to the model.
    pub fn file_content() -> Self {
        Self::FileContent(InputFileContentParam::default())
    }
}
///A text input to the model.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct InputTextContent {
    ///The text input to the model.
    #[validate(length(min = 1u64))]
    pub text: String,
    ///The type of the input item. Always `input_text`.
    #[serde(rename = "type")]
    #[default(Some("input_text".to_string()))]
    pub r#type: Option<String>,
}
///A text input to the model.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct InputTextContentParam {
    ///The text input to the model.
    #[validate(length(max = 10_485_760u64))]
    pub text: String,
    ///The type of the input item. Always `input_text`.
    #[serde(rename = "type")]
    #[default(Some("input_text".to_string()))]
    pub r#type: Option<String>,
}
///A breakdown of input token usage that was recorded.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
pub struct InputTokensDetails {
    ///The number of input tokens that were served from cache.
    pub cached_tokens: i64,
}
///A content block representing a video input to the model.
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct InputVideoContent {
    ///The type of the input content. Always `input_video`.
    #[serde(rename = "type")]
    #[default("input_video".to_string())]
    pub r#type: String,
    ///A base64 or remote url that resolves to a video file.
    #[validate(length(min = 1u64))]
    pub video_url: String,
}
///An item representing a message, tool call, tool output, reasoning, or other response element.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum ItemField {
    ///A message to or from the model.
    #[default]
    Message(Message),
    ///A function tool call that was generated by the model.
    FunctionCall(FunctionCall),
    ///A function tool call output that was returned by the tool.
    FunctionCallOutput(FunctionCallOutput),
    ///A reasoning item that was generated by the model.
    ReasoningBody(ReasoningBody),
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum ItemParam {
    ///An internal identifier for an item to reference.
    #[default]
    ItemReference(ItemReferenceParam),
    ReasoningItem(ReasoningItemParam),
    UserMessageItem(UserMessageItemParam),
    SystemMessageItem(SystemMessageItemParam),
    DeveloperMessageItem(DeveloperMessageItemParam),
    AssistantMessageItem(AssistantMessageItemParam),
    FunctionCallItem(FunctionCallItemParam),
    ///The output of a function tool call.
    FunctionCallOutputItem(FunctionCallOutputItemParam),
}
impl ItemParam {
    ///An internal identifier for an item to reference.
    pub fn reference(id: String) -> Self {
        Self::ItemReference(ItemReferenceParam {
            id,
            ..Default::default()
        })
    }
    pub fn reasoning(summary: Vec<ReasoningSummaryContentParam>) -> Self {
        Self::ReasoningItem(ReasoningItemParam {
            summary,
            ..Default::default()
        })
    }
    pub fn user_message(content: UserMessageItemParamContent) -> Self {
        Self::UserMessageItem(UserMessageItemParam {
            content,
            ..Default::default()
        })
    }
    pub fn system_message(content: MessageItemParamContent) -> Self {
        Self::SystemMessageItem(SystemMessageItemParam {
            content,
            ..Default::default()
        })
    }
    pub fn developer_message(content: MessageItemParamContent) -> Self {
        Self::DeveloperMessageItem(DeveloperMessageItemParam {
            content,
            ..Default::default()
        })
    }
    pub fn assistant_message(content: AssistantMessageItemParamContent) -> Self {
        Self::AssistantMessageItem(AssistantMessageItemParam {
            content,
            ..Default::default()
        })
    }
}
///An internal identifier for an item to reference.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
pub struct ItemReferenceParam {
    ///The ID of the item to reference.
    #[validate(length(min = 1u64))]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct JsonObjectResponseFormat {
    #[serde(rename = "type")]
    #[default(Some("json_object".to_string()))]
    pub r#type: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct JsonSchemaResponseFormat {
    pub description: Option<String>,
    #[validate(length(min = 1u64))]
    pub name: String,
    pub schema: JsonSchemaResponseFormatSchema,
    pub strict: bool,
    #[serde(rename = "type")]
    #[default(Some("json_schema".to_string()))]
    pub r#type: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct JsonSchemaResponseFormatParam {
    ///A description of what the response format is for, used by the model to
    ///determine how to respond in the format.
    pub description: Option<String>,
    ///The name of the response format. Must be a-z, A-Z, 0-9, or contain
    ///underscores and dashes, with a maximum length of 64.
    pub name: Option<String>,
    ///The schema for the response format, described as a JSON Schema object.
    pub schema: Option<std::collections::HashMap<String, serde_json::Value>>,
    pub strict: Option<bool>,
    ///The type of response format being defined. Always `json_schema`.
    #[serde(rename = "type")]
    #[default(Some("json_schema".to_string()))]
    pub r#type: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct JsonSchemaResponseFormatSchema {}

impl Default for JsonSchemaResponseFormatSchema {
    fn default() -> Self {
        Self{}
    }
}

///The log probability of a token.
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
pub struct LogProb {
    pub bytes: Vec<i64>,
    pub logprob: f64,
    #[validate(length(min = 1u64))]
    pub token: String,
    #[validate(nested)]
    pub top_logprobs: Vec<TopLogProb>,
}
///A message to or from the model.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct Message {
    ///The content of the message
    pub content: Vec<ContentKind>,
    ///The unique ID of the message.
    pub id: String,
    pub role: serde_json::Value,
    pub status: serde_json::Value,
    ///The type of the message. Always set to `message`.
    #[serde(rename = "type")]
    #[default(Some("message".to_string()))]
    pub r#type: Option<String>,
}
///The message content, as an array of content parts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum MessageItemParamContent {
    #[default]
    Array(Vec<ArrayKind2>),
    ///The message content, as a single string.
    String(String),
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum MessageRole {
    #[serde(rename = "user")]
    #[default]
    User,
    #[serde(rename = "assistant")]
    Assistant,
    #[serde(rename = "system")]
    System,
    #[serde(rename = "developer")]
    Developer,
}
impl core::fmt::Display for MessageRole {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::User => write!(f, "user"),
            Self::Assistant => write!(f, "assistant"),
            Self::System => write!(f, "system"),
            Self::Developer => write!(f, "developer"),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum MessageStatus {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "incomplete")]
    Incomplete,
}
impl core::fmt::Display for MessageStatus {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InProgress => write!(f, "in_progress"),
            Self::Completed => write!(f, "completed"),
            Self::Incomplete => write!(f, "incomplete"),
        }
    }
}
///Set of 16 key-value pairs that can be attached to an object. This can be         useful for storing additional information about the object in a structured         format, and querying for objects via API or the dashboard.
///        Keys are strings with a maximum length of 64 characters. Values are strings         with a maximum length of 512 characters.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
pub struct MetadataParam {
    ///Additional properties not defined in the schema.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, String>,
}
///A text output from the model.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct OutputTextContent {
    ///The annotations of the text output.
    #[validate(nested)]
    pub annotations: Vec<UrlCitationBody>,
    #[validate(nested)]
    pub logprobs: Vec<LogProb>,
    ///The text output from the model.
    #[validate(length(min = 1u64))]
    pub text: String,
    ///The type of the output text. Always `output_text`.
    #[serde(rename = "type")]
    #[default(Some("output_text".to_string()))]
    pub r#type: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct OutputTextContentParam {
    ///Citations associated with the text content.
    pub annotations: Option<OutputTextContentParamAnnotations>,
    ///The text content.
    #[validate(length(max = 10_485_760u64))]
    pub text: String,
    ///The content type. Always `output_text`.
    #[serde(rename = "type")]
    #[default(Some("output_text".to_string()))]
    pub r#type: Option<String>,
}
///Citations associated with the text content.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum OutputTextContentParamAnnotations {
    #[default]
    Array(Vec<UrlCitationParam>),
}
///A breakdown of output token usage that was recorded.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
pub struct OutputTokensDetails {
    ///The number of output tokens that were attributed to reasoning.
    pub reasoning_tokens: i64,
}
///Reasoning configuration and metadata that were used for the response.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
pub struct Reasoning {
    pub effort: Option<ReasoningEffortEnum>,
    pub summary: Option<serde_json::Value>,
}
///A reasoning item that was generated by the model.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct ReasoningBody {
    ///The reasoning content that was generated.
    pub content: Option<Vec<StreamingEventPart>>,
    ///The encrypted reasoning content that was generated.
    pub encrypted_content: Option<String>,
    ///The unique ID of the reasoning item.
    pub id: String,
    ///The reasoning summary content that was generated.
    pub summary: Vec<StreamingEventPart>,
    ///The type of the item. Always `reasoning`.
    #[serde(rename = "type")]
    #[default(Some("reasoning".to_string()))]
    pub r#type: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum ReasoningEffortEnum {
    #[serde(rename = "none")]
    #[default]
    None,
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "xhigh")]
    Xhigh,
}
impl core::fmt::Display for ReasoningEffortEnum {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::Low => write!(f, "low"),
            Self::Medium => write!(f, "medium"),
            Self::High => write!(f, "high"),
            Self::Xhigh => write!(f, "xhigh"),
        }
    }
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ReasoningItemParam {
    pub content: Option<JsonSchemaResponseFormatSchema>,
    pub encrypted_content: Option<String>,
    pub id: Option<String>,
    ///Reasoning summary content associated with this item.
    #[validate(nested)]
    pub summary: Vec<ReasoningSummaryContentParam>,
    ///The item type. Always `reasoning`.
    #[serde(rename = "type")]
    #[default(Some("reasoning".to_string()))]
    pub r#type: Option<String>,
}
///**gpt-5 and o-series models only** Configuration options for [reasoning models](https://platform.openai.com/docs/guides/reasoning).
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
pub struct ReasoningParam {
    pub effort: Option<ReasoningEffortEnum>,
    pub summary: Option<serde_json::Value>,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ReasoningSummaryContentParam {
    ///The reasoning summary text.
    #[validate(length(max = 10_485_760u64))]
    pub text: String,
    ///The content type. Always `summary_text`.
    #[serde(rename = "type")]
    #[default(Some("summary_text".to_string()))]
    pub r#type: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum ReasoningSummaryEnum {
    #[serde(rename = "concise")]
    #[default]
    Concise,
    #[serde(rename = "detailed")]
    Detailed,
    #[serde(rename = "auto")]
    Auto,
}
impl core::fmt::Display for ReasoningSummaryEnum {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Concise => write!(f, "concise"),
            Self::Detailed => write!(f, "detailed"),
            Self::Auto => write!(f, "auto"),
        }
    }
}
///Reasoning text from the model.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ReasoningTextContent {
    ///The reasoning text from the model.
    #[validate(length(min = 1u64))]
    pub text: String,
    ///The type of the reasoning text. Always `reasoning_text`.
    #[serde(rename = "type")]
    #[default(Some("reasoning_text".to_string()))]
    pub r#type: Option<String>,
}
///A refusal from the model.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct RefusalContent {
    ///The refusal explanation from the model.
    #[validate(length(min = 1u64))]
    pub refusal: String,
    ///The type of the refusal. Always `refusal`.
    #[serde(rename = "type")]
    #[default(Some("refusal".to_string()))]
    pub r#type: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct RefusalContentParam {
    ///The refusal text.
    #[validate(length(max = 10_485_760u64))]
    pub refusal: String,
    ///The content type. Always `refusal`.
    #[serde(rename = "type")]
    #[default(Some("refusal".to_string()))]
    pub r#type: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum Response200Response {
    ///A streaming event that indicated the response was created.
    #[default]
    ResponseCreated(ResponseCreatedStreamingEvent),
    ///A streaming event that indicated the response was queued.
    ResponseQueued(ResponseQueuedStreamingEvent),
    ///A streaming event that indicated the response was in progress.
    ResponseInProgress(ResponseInProgressStreamingEvent),
    ///A streaming event that indicated the response was completed.
    ResponseCompleted(ResponseCompletedStreamingEvent),
    ///A streaming event that indicated the response had failed.
    ResponseFailed(ResponseFailedStreamingEvent),
    ///A streaming event that indicated the response was incomplete.
    ResponseIncomplete(ResponseIncompleteStreamingEvent),
    ///A streaming event that indicated an output item was added to the response.
    ResponseOutputItemAdded(ResponseOutputItemAddedStreamingEvent),
    ///A streaming event that indicated an output item was completed.
    ResponseOutputItemDone(ResponseOutputItemDoneStreamingEvent),
    ///A streaming event that indicated a reasoning summary part was added.
    ResponseReasoningSummaryPartAdded(ResponseReasoningSummaryPartAddedStreamingEvent),
    ///A streaming event that indicated a reasoning summary part was completed.
    ResponseReasoningSummaryPartDone(ResponseReasoningSummaryPartDoneStreamingEvent),
    ///A streaming event that indicated a content part was added.
    ResponseContentPartAdded(ResponseContentPartAddedStreamingEvent),
    ///A streaming event that indicated a content part was completed.
    ResponseContentPartDone(ResponseContentPartDoneStreamingEvent),
    ///A streaming event that indicated output text was incrementally added.
    ResponseOutputTextDelta(ResponseOutputTextDeltaStreamingEvent),
    ///A streaming event that indicated output text was completed.
    ResponseOutputTextDone(ResponseOutputTextDoneStreamingEvent),
    ///A streaming event that indicated refusal text was incrementally added.
    ResponseRefusalDelta(ResponseRefusalDeltaStreamingEvent),
    ///A streaming event that indicated refusal text was completed.
    ResponseRefusalDone(ResponseRefusalDoneStreamingEvent),
    ///A streaming event that indicated reasoning text was incrementally added.
    ResponseReasoningDelta(ResponseReasoningDeltaStreamingEvent),
    ///A streaming event that indicated reasoning text was completed.
    ResponseReasoningDone(ResponseReasoningDoneStreamingEvent),
    ///A streaming event that indicated a reasoning summary was incrementally added.
    ResponseReasoningSummaryDelta(ResponseReasoningSummaryDeltaStreamingEvent),
    ///A streaming event that indicated a reasoning summary was completed.
    ResponseReasoningSummaryDone(ResponseReasoningSummaryDoneStreamingEvent),
    ///A streaming event that indicated an output text annotation was added.
    ResponseOutputTextAnnotationAdded(ResponseOutputTextAnnotationAddedStreamingEvent),
    ///A streaming event that indicated function call arguments were incrementally added.
    ResponseFunctionCallArgumentsDelta(ResponseFunctionCallArgumentsDeltaStreamingEvent),
    ///A streaming event that indicated function call arguments were completed.
    ResponseFunctionCallArgumentsDone(ResponseFunctionCallArgumentsDoneStreamingEvent),
    ///A streaming event that indicated an error was emitted.
    Error(ErrorStreamingEvent),
}
///A streaming event that indicated the response was completed.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct ResponseCompletedStreamingEvent {
    pub response: serde_json::Value,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.completed`.
    #[serde(rename = "type")]
    #[default(Some("response.completed".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated a content part was added.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseContentPartAddedStreamingEvent {
    ///The index of the content part that was added.
    pub content_index: i64,
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///A content part that makes up an input or output item.
    pub part: StreamingEventPart,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.content_part.added`.
    #[serde(rename = "type")]
    #[default(Some("response.content_part.added".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated a content part was completed.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseContentPartDoneStreamingEvent {
    ///The index of the content part that was completed.
    pub content_index: i64,
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///A content part that makes up an input or output item.
    pub part: StreamingEventPart,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.content_part.done`.
    #[serde(rename = "type")]
    #[default(Some("response.content_part.done".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated the response was created.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct ResponseCreatedStreamingEvent {
    pub response: serde_json::Value,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.created`.
    #[serde(rename = "type")]
    #[default(Some("response.created".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated the response had failed.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct ResponseFailedStreamingEvent {
    pub response: serde_json::Value,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.failed`.
    #[serde(rename = "type")]
    #[default(Some("response.failed".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated function call arguments were incrementally added.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseFunctionCallArgumentsDeltaStreamingEvent {
    ///The arguments delta that was appended.
    #[validate(length(min = 1u64))]
    pub delta: String,
    ///The ID of the tool call item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///An obfuscation string that was added to pad the event payload.
    pub obfuscation: Option<String>,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.function_call_arguments.delta`.
    #[serde(rename = "type")]
    #[default(Some("response.function_call_arguments.delta".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated function call arguments were completed.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseFunctionCallArgumentsDoneStreamingEvent {
    ///The final arguments string that was emitted.
    #[validate(length(min = 1u64))]
    pub arguments: String,
    ///The ID of the tool call item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.function_call_arguments.done`.
    #[serde(rename = "type")]
    #[default(Some("response.function_call_arguments.done".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated the response was in progress.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct ResponseInProgressStreamingEvent {
    pub response: serde_json::Value,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.in_progress`.
    #[serde(rename = "type")]
    #[default(Some("response.in_progress".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated the response was incomplete.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct ResponseIncompleteStreamingEvent {
    pub response: serde_json::Value,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.incomplete`.
    #[serde(rename = "type")]
    #[default(Some("response.incomplete".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated an output item was added to the response.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct ResponseOutputItemAddedStreamingEvent {
    pub item: Option<serde_json::Value>,
    ///The index of the output item that was added.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.output_item.added`.
    #[serde(rename = "type")]
    #[default(Some("response.output_item.added".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated an output item was completed.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct ResponseOutputItemDoneStreamingEvent {
    pub item: Option<serde_json::Value>,
    ///The index of the output item that was completed.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.output_item.done`.
    #[serde(rename = "type")]
    #[default(Some("response.output_item.done".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated an output text annotation was added.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseOutputTextAnnotationAddedStreamingEvent {
    pub annotation: Option<serde_json::Value>,
    ///The index of the annotation that was added.
    pub annotation_index: i64,
    ///The index of the output text content that was updated.
    pub content_index: i64,
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.output_text.annotation.added`.
    #[serde(rename = "type")]
    #[default(Some("response.output_text.annotation.added".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated output text was incrementally added.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseOutputTextDeltaStreamingEvent {
    ///The index of the content part that was updated.
    pub content_index: i64,
    ///The text delta that was appended.
    #[validate(length(min = 1u64))]
    pub delta: String,
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The token log probabilities that were emitted with the delta, if any.
    #[validate(nested)]
    pub logprobs: Vec<LogProb>,
    ///An obfuscation string that was added to pad the event payload.
    pub obfuscation: Option<String>,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.output_text.delta`.
    #[serde(rename = "type")]
    #[default(Some("response.output_text.delta".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated output text was completed.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseOutputTextDoneStreamingEvent {
    ///The index of the content part that was completed.
    pub content_index: i64,
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The token log probabilities that were emitted with the final text, if any.
    #[validate(nested)]
    pub logprobs: Vec<LogProb>,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The final text that was emitted.
    #[validate(length(min = 1u64))]
    pub text: String,
    ///The type of the event, always `response.output_text.done`.
    #[serde(rename = "type")]
    #[default(Some("response.output_text.done".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated the response was queued.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct ResponseQueuedStreamingEvent {
    pub response: serde_json::Value,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.queued`.
    #[serde(rename = "type")]
    #[default(Some("response.queued".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated reasoning text was incrementally added.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseReasoningDeltaStreamingEvent {
    ///The index of the reasoning content that was updated.
    pub content_index: i64,
    ///The reasoning text delta that was appended.
    #[validate(length(min = 1u64))]
    pub delta: String,
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///An obfuscation string that was added to pad the event payload.
    pub obfuscation: Option<String>,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.reasoning.delta`.
    #[serde(rename = "type")]
    #[default(Some("response.reasoning.delta".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated reasoning text was completed.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseReasoningDoneStreamingEvent {
    ///The index of the reasoning content that was completed.
    pub content_index: i64,
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The final reasoning text that was emitted.
    #[validate(length(min = 1u64))]
    pub text: String,
    ///The type of the event, always `response.reasoning.done`.
    #[serde(rename = "type")]
    #[default(Some("response.reasoning.done".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated a reasoning summary was incrementally added.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseReasoningSummaryDeltaStreamingEvent {
    ///The summary text delta that was appended.
    #[validate(length(min = 1u64))]
    pub delta: String,
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///An obfuscation string that was added to pad the event payload.
    pub obfuscation: Option<String>,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The index of the summary content that was updated.
    pub summary_index: i64,
    ///The type of the event, always `response.reasoning_summary.delta`.
    #[serde(rename = "type")]
    #[default(Some("response.reasoning_summary_text.delta".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated a reasoning summary was completed.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseReasoningSummaryDoneStreamingEvent {
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The index of the summary content that was completed.
    pub summary_index: i64,
    ///The final summary text that was emitted.
    #[validate(length(min = 1u64))]
    pub text: String,
    ///The type of the event, always `response.reasoning_summary.done`.
    #[serde(rename = "type")]
    #[default(Some("response.reasoning_summary_text.done".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated a reasoning summary part was added.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseReasoningSummaryPartAddedStreamingEvent {
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///A content part that makes up an input or output item.
    pub part: StreamingEventPart,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The index of the summary part that was added.
    pub summary_index: i64,
    ///The type of the event, always `response.reasoning_summary_part.added`.
    #[serde(rename = "type")]
    #[default(Some("response.reasoning_summary_part.added".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated a reasoning summary part was completed.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseReasoningSummaryPartDoneStreamingEvent {
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///A content part that makes up an input or output item.
    pub part: StreamingEventPart,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The index of the summary part that was completed.
    pub summary_index: i64,
    ///The type of the event, always `response.reasoning_summary_part.done`.
    #[serde(rename = "type")]
    #[default(Some("response.reasoning_summary_part.done".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated refusal text was incrementally added.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseRefusalDeltaStreamingEvent {
    ///The index of the refusal content that was updated.
    pub content_index: i64,
    ///The refusal text delta that was appended.
    #[validate(length(min = 1u64))]
    pub delta: String,
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.refusal.delta`.
    #[serde(rename = "type")]
    #[default(Some("response.refusal.delta".to_string()))]
    pub r#type: Option<String>,
}
///A streaming event that indicated refusal text was completed.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct ResponseRefusalDoneStreamingEvent {
    ///The index of the refusal content that was completed.
    pub content_index: i64,
    ///The ID of the item that was updated.
    #[validate(length(min = 1u64))]
    pub item_id: String,
    ///The index of the output item that was updated.
    pub output_index: i64,
    ///The final refusal text that was emitted.
    #[validate(length(min = 1u64))]
    pub refusal: String,
    ///The sequence number of the event that was emitted.
    pub sequence_number: i64,
    ///The type of the event, always `response.refusal.done`.
    #[serde(rename = "type")]
    #[default(Some("response.refusal.done".to_string()))]
    pub r#type: Option<String>,
}
///The complete response object that was returned by the Responses API.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct ResponseResource {
    ///Whether this request was run in the background.
    pub background: bool,
    pub completed_at: Option<i64>,
    ///The Unix timestamp (in seconds) for when the response was created.
    pub created_at: i64,
    pub error: Option<serde_json::Value>,
    ///The frequency penalty that was used to penalize new tokens based on their frequency in the text so far.
    pub frequency_penalty: f64,
    ///The unique ID of the response that was created.
    pub id: String,
    pub incomplete_details: Option<serde_json::Value>,
    pub instructions: Option<String>,
    pub max_output_tokens: Option<i64>,
    pub max_tool_calls: Option<i64>,
    ///Developer-defined metadata that was associated with the response.
    pub metadata: serde_json::Value,
    ///The model that generated this response.
    pub model: String,
    ///The object type, which was always `response`.
    #[default(Some("response".to_string()))]
    pub object: Option<String>,
    ///The output items that were generated by the model.
    pub output: Vec<ItemField>,
    ///Whether the model was allowed to call multiple tools in parallel.
    pub parallel_tool_calls: bool,
    ///The presence penalty that was used to penalize new tokens based on whether they appear in the text so far.
    pub presence_penalty: f64,
    pub previous_response_id: Option<String>,
    pub prompt_cache_key: Option<String>,
    pub reasoning: Option<serde_json::Value>,
    pub safety_identifier: Option<String>,
    ///The service tier that was used for this response.
    pub service_tier: String,
    ///The status that was set for the response.
    pub status: String,
    ///Whether this response was stored so it can be retrieved later.
    pub store: bool,
    ///The sampling temperature that was used for this response.
    pub temperature: f64,
    pub text: serde_json::Value,
    pub tool_choice: ResponseResourceToolChoice,
    ///The tools that were available to the model during response generation.
    pub tools: Vec<FunctionTool>,
    ///The number of most likely tokens that were returned at each position, along with their log probabilities.
    pub top_logprobs: i64,
    ///The nucleus sampling parameter that was used for this response.
    pub top_p: f64,
    pub truncation: serde_json::Value,
    pub usage: Option<serde_json::Value>,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum ResponseResourceToolChoice {
    #[default]
    FunctionToolChoice(FunctionToolChoice),
    ToolChoiceValueEnum(ToolChoiceValueEnum),
    AllowedToolChoice(AllowedToolChoice),
}
impl ResponseResourceToolChoice {
    pub fn function() -> Self {
        Self::FunctionToolChoice(FunctionToolChoice::default())
    }
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum ResponsesToolParam {
    #[default]
    FunctionToolParam(FunctionToolParam),
}
impl ResponsesToolParam {
    pub fn function(name: String) -> Self {
        Self::FunctionToolParam(FunctionToolParam {
            name,
            ..Default::default()
        })
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum ServiceTierEnum {
    #[serde(rename = "auto")]
    #[default]
    Auto,
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "flex")]
    Flex,
    #[serde(rename = "priority")]
    Priority,
}
impl core::fmt::Display for ServiceTierEnum {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Auto => write!(f, "auto"),
            Self::Default => write!(f, "default"),
            Self::Flex => write!(f, "flex"),
            Self::Priority => write!(f, "priority"),
        }
    }
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct SpecificFunctionParam {
    ///The name of the function tool to call.
    #[validate(length(min = 1u64))]
    pub name: String,
    ///The tool to call. Always `function`.
    #[serde(rename = "type")]
    #[default(Some("function".to_string()))]
    pub r#type: Option<String>,
}
///Options that control streamed response behavior.
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
pub struct StreamOptionsParam {
    ///Whether to obfuscate sensitive information in streamed output. Defaults to `true`.
    pub include_obfuscation: Option<bool>,
}
///A content part that makes up an input or output item.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum StreamingEventPart {
    ///A text input to the model.
    #[default]
    InputText(InputTextContent),
    ///A text output from the model.
    OutputText(OutputTextContent),
    ///A text content.
    Text(TextContent),
    ///A summary text from the model.
    SummaryText(SummaryTextContent),
    ///Reasoning text from the model.
    ReasoningText(ReasoningTextContent),
    ///A refusal from the model.
    Refusal(RefusalContent),
    ///An image input to the model. Learn about [image inputs](/docs/guides/vision).
    InputImage(InputImageContent),
    ///A file input to the model.
    InputFile(InputFileContent),
}
impl StreamingEventPart {
    ///A text input to the model.
    pub fn input_text(text: String) -> Self {
        Self::InputText(InputTextContent {
            text,
            ..Default::default()
        })
    }
    ///A text content.
    pub fn text(text: String) -> Self {
        Self::Text(TextContent {
            text,
            ..Default::default()
        })
    }
    ///A summary text from the model.
    pub fn summary_text(text: String) -> Self {
        Self::SummaryText(SummaryTextContent {
            text,
            ..Default::default()
        })
    }
    ///Reasoning text from the model.
    pub fn reasoning_text(text: String) -> Self {
        Self::ReasoningText(ReasoningTextContent {
            text,
            ..Default::default()
        })
    }
    ///A refusal from the model.
    pub fn refusal(refusal: String) -> Self {
        Self::Refusal(RefusalContent {
            refusal,
            ..Default::default()
        })
    }
    ///An image input to the model. Learn about [image inputs](/docs/guides/vision).
    pub fn input_image(detail: serde_json::Value) -> Self {
        Self::InputImage(InputImageContent {
            detail,
            ..Default::default()
        })
    }
    ///A file input to the model.
    pub fn input_file() -> Self {
        Self::InputFile(InputFileContent::default())
    }
}
///A summary text from the model.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct SummaryTextContent {
    ///A summary of the reasoning output from the model so far.
    #[validate(length(min = 1u64))]
    pub text: String,
    ///The type of the object. Always `summary_text`.
    #[serde(rename = "type")]
    #[default(Some("summary_text".to_string()))]
    pub r#type: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct SystemMessageItemParam {
    ///The message content, as an array of content parts.
    pub content: MessageItemParamContent,
    pub id: Option<String>,
    ///The message role. Always `system`.
    #[default(Some("system".to_string()))]
    pub role: Option<String>,
    pub status: Option<String>,
    ///The item type. Always `message`.
    #[serde(rename = "type")]
    #[default(Some("message".to_string()))]
    pub r#type: Option<String>,
}
///A text content.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct TextContent {
    #[validate(length(min = 1u64))]
    pub text: String,
    #[serde(rename = "type")]
    #[default(Some("text".to_string()))]
    pub r#type: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
pub struct TextField {
    pub format: TextFieldFormat,
    pub verbosity: Option<VerbosityEnum>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum TextFieldFormat {
    #[default]
    Text(TextResponseFormat),
    JsonObject(JsonObjectResponseFormat),
    JsonSchema(JsonSchemaResponseFormat),
}
impl TextFieldFormat {
    pub fn text(r#type: Option<String>) -> Self {
        Self::Text(TextResponseFormat {
            r#type,
            ..Default::default()
        })
    }
    pub fn json_object(r#type: Option<String>) -> Self {
        Self::JsonObject(JsonObjectResponseFormat {
            r#type,
            ..Default::default()
        })
    }
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum TextFormatParam {
    #[default]
    TextResponseFormat(TextResponseFormat),
    JsonSchemaResponseFormatParam(JsonSchemaResponseFormatParam),
}
impl TextFormatParam {
    pub fn response(r#type: Option<String>) -> Self {
        Self::TextResponseFormat(TextResponseFormat {
            r#type,
            ..Default::default()
        })
    }
    pub fn json_schema_response() -> Self {
        Self::JsonSchemaResponseFormatParam(JsonSchemaResponseFormatParam::default())
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
pub struct TextParam {
    ///The format configuration for text output.
    pub format: Option<Box<TextFormatParam>>,
    pub verbosity: Option<serde_json::Value>,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct TextResponseFormat {
    #[serde(rename = "type")]
    #[default(Some("text".to_string()))]
    pub r#type: Option<String>,
}
///A tool that can be used to generate a response.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum Tool {
    ///Defines a function in your own code the model can choose to call. Learn more about [function calling](https://platform.openai.com/docs/guides/function-calling).
    #[default]
    FunctionTool(FunctionTool),
}
impl Tool {
    ///Defines a function in your own code the model can choose to call. Learn more about [function calling](https://platform.openai.com/docs/guides/function-calling).
    pub fn function(name: String) -> Self {
        Self::FunctionTool(FunctionTool {
            name,
            ..Default::default()
        })
    }
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum SpecificToolChoiceParam{
    #[default]
    SpecificFunctionParam(SpecificFunctionParam),
}
///Controls which tool the model should use, if any.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum ToolChoiceParam {
    #[default]
    SpecificToolChoiceParam(SpecificToolChoiceParam),
    ToolChoiceValueEnum(ToolChoiceValueEnum),
    AllowedToolsParam(AllowedToolsParam),
}
impl ToolChoiceParam {
    pub fn allowed_tools(tools: Vec<SpecificFunctionParam>) -> Self {
        Self::AllowedToolsParam(AllowedToolsParam {
            tools,
            ..Default::default()
        })
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum ToolChoiceValueEnum {
    #[serde(rename = "none")]
    #[default]
    None,
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "required")]
    Required,
}
impl core::fmt::Display for ToolChoiceValueEnum {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::Auto => write!(f, "auto"),
            Self::Required => write!(f, "required"),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum ToolKind {
    #[default]
    FunctionToolChoice(FunctionToolChoice),
}
impl ToolKind {
    pub fn function_choice() -> Self {
        Self::FunctionToolChoice(FunctionToolChoice::default())
    }
}
///The top log probability of a token.
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
pub struct TopLogProb {
    pub bytes: Vec<i64>,
    pub logprob: f64,
    #[validate(length(min = 1u64))]
    pub token: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum TruncationEnum {
    #[serde(rename = "auto")]
    #[default]
    Auto,
    #[serde(rename = "disabled")]
    Disabled,
}
impl core::fmt::Display for TruncationEnum {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Auto => write!(f, "auto"),
            Self::Disabled => write!(f, "disabled"),
        }
    }
}
///A citation for a web resource used to generate a model response.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct UrlCitationBody {
    ///The index of the last character of the URL citation in the message.
    pub end_index: i64,
    ///The index of the first character of the URL citation in the message.
    pub start_index: i64,
    ///The title of the web resource.
    #[validate(length(min = 1u64))]
    pub title: String,
    ///The type of the URL citation. Always `url_citation`.
    #[serde(rename = "type")]
    #[default(Some("url_citation".to_string()))]
    pub r#type: Option<String>,
    ///The URL of the web resource.
    #[validate(length(min = 1u64))]
    pub url: String,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(default)]
pub struct UrlCitationParam {
    ///The index of the last character of the citation in the message.
    #[validate(range(min = 0i64))]
    pub end_index: i64,
    ///The index of the first character of the citation in the message.
    #[validate(range(min = 0i64))]
    pub start_index: i64,
    ///The title of the cited resource.
    #[validate(length(min = 1u64))]
    pub title: String,
    ///The citation type. Always `url_citation`.
    #[serde(rename = "type")]
    #[default(Some("url_citation".to_string()))]
    pub r#type: Option<String>,
    ///The URL of the cited resource.
    #[validate(length(min = 1u64))]
    pub url: String,
}
///Token usage statistics that were recorded for the response.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
pub struct Usage {
    ///The number of input tokens that were used to generate the response.
    pub input_tokens: i64,
    pub input_tokens_details: serde_json::Value,
    ///The number of output tokens that were generated by the model.
    pub output_tokens: i64,
    pub output_tokens_details: serde_json::Value,
    ///The total number of tokens that were used.
    pub total_tokens: i64,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct UserMessageItemParam {
    ///The message content, as an array of content parts.
    pub content: UserMessageItemParamContent,
    pub id: Option<String>,
    ///The message role. Always `user`.
    #[default(Some("user".to_string()))]
    pub role: Option<String>,
    pub status: Option<String>,
    ///The item type. Always `message`.
    #[serde(rename = "type")]
    #[default(Some("message".to_string()))]
    pub r#type: Option<String>,
}
///The message content, as an array of content parts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub enum UserMessageItemParamContent {
    #[default]
    Array(Vec<InputParamKind>),
    ///The message content, as a single string.
    String(String),
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, oas3_gen_support::Default)]
pub enum VerbosityEnum {
    #[serde(rename = "low")]
    #[default]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
}
impl core::fmt::Display for VerbosityEnum {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Low => write!(f, "low"),
            Self::Medium => write!(f, "medium"),
            Self::High => write!(f, "high"),
        }
    }
}
